export const ADD_PRODUCT_BASKET = "ADD_PRODUCT_BASKET";
export const GET_NUMBERS_BASKET = "GET_NUMBERS_BASKET";
export const SEARCH_PRODUCT = "SEARCH_PRODUCT";
export const GET_SEARCH_PRODUCT = "GET_SEARCH_PRODUCT";
